### PR TITLE
[Bug Fix] Exception handling in Filter and delete commands

### LINKED ISSUE #296: [PE-D][Tester D] Typo when deleting multiple courses
Expected: provide just one index
Actual: provide a just one index

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jadenlimjc/ped#11

### LINKED ISSUE #318: Allow for special NUS course codes for filter command
There are some course codes, such as EE3131C, with the extra character 'C' which are not counted as valid input currently.

### PR DESCRIPTION
**Pull request by chewycj**
Fixes #318 
Fixes #296

### CODE REVIEW

File: src/main/java/seedu/exchangecoursemapper/constants/Commands.java [hunk 1]
```diff
@@ -18,5 +18,8 @@ public class Commands {
     public static final int PLAN_INDEX_TO_DELETE = 1;
     public static final int FILTER_COURSES_MAX_ARGS = 2;
     public static final int ZERO_INDEX_OFFSET = 1;
+    public static final int NUS_COURSE_CODE_LENGTH = 6;
+    public static final int NUS_SPECIAL_COURSE_CODE_LENGTH = 7;
+    public static final int NUS_COURSE_CODE_NUMERALS_START_INDEX = 2;
```
Comment (hzxnancy) [inline src/main/java/seedu/exchangecoursemapper/constants/Commands.java:23]: Good extraction of variables!

**Review by hzxnancy — APPROVED** [review]
LGTM!
