### PR TITLE
[BugFix] Fix bugs on list schools

### LINKED ISSUE #48: Fix bugs on List Schools

### PR DESCRIPTION
**Pull request by louisjoety**
###  Ensure consistent file naming

Fixes #48

### CODE REVIEW

File: src/main/java/seedu/exchangecoursemapper/ui/UI.java [hunk 1]
```diff
@@ -14,6 +14,11 @@ public void displayGreeting() {
         System.out.println(greetingMessage);
     }
 
+    public void displayExitMessage() {
+        String exitMessage = "All the best in planning for your exchange, hope we helped!";
+        System.out.println(exitMessage);
+    }
+
```
Comment (chewycj) [inline src/main/java/seedu/exchangecoursemapper/ui/UI.java:21]: I like that you extracted out the user interaction for the goodbye message into the UI class for better cohesion!

**Review by chewycj — APPROVED** [review]
LGTM!! The changes improve the code design 👍
