### PR TITLE
[Improvement] Fix bugs and implement OOP in FilterCourses and DeleteCourses

### LINKED ISSUE #215: Implement more error handling and OOP in FilterCourses and DeleteCourses
- Add code to check if user input is a NUS SoC course
- Refactor parts of the code for both commands
- Modify JUnit tests accordingly

### PR DESCRIPTION
**Pull request by chewycj**
FIxes #215 

- DeleteCoursesCommandTest: Remove any changes made to the myList.json file

### CODE REVIEW

File: src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java [hunk 1]
```diff
@@ -28,19 +29,66 @@ public void setUp() {
...
+
+    @Test
+    public void isValidSocCourseCode_inputWithEeCourseCode_expectTrue() {
+        String userInput = "ee2026";
+        boolean isValidSocCourseCode = filterCoursesCommand.isValidSocCourseCode(userInput);
+        assertTrue(isValidSocCourseCode);
+    }
+
+    @Test
+    public void isValidSocCourseCode_inputWithBtCourseCode_expectTrue() {
```
Comment (louisjoety) [inline src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java:73]: How about CG coded mods?

Comment (louisjoety) [inline src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java:73]: Could this be repeated testing as the outcome is the same?

File: src/main/java/seedu/exchangecoursemapper/command/Command.java [hunk 2]
```diff
@@ -6,6 +6,9 @@
 import java.io.IOException;
 import java.io.InputStream;
 
+/**
+ * Command class is an abstract base class representing a command that can be executed by ExchangeCourseMapper,
+ */
```
Comment (louisjoety) [inline src/main/java/seedu/exchangecoursemapper/command/Command.java:11]: 👍

**Review by louisjoety — COMMENTED** [review]
🤣

File: src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java (hunk 1 above)
Comment (chewycj) [reply src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java:73]: Thanks for catching that!! I will add it into the conditions 👍

Comment (chewycj) [reply src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java:73]: For this, I was thinking to test if the code works for every SoC coded module! But I agree it might be repeated testing, hence I would change this part to a test for a non SoC coded module!

File: src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java [hunk 3]
```diff
@@ -28,19 +30,66 @@ public void setUp() {
...
+        boolean isValidSocCourseCode = filterCoursesCommand.isValidSocCourseCode(userInput);
+        assertTrue(isValidSocCourseCode);
+    }
+
+    @Test
+    public void isValidSocCourseCode_inputWithIsCourseCode_expectTrue() {
+        String userInput = "gess1000";
+        boolean isValidSocCourseCode = filterCoursesCommand.isValidSocCourseCode(userInput);
+        assertFalse(isValidSocCourseCode);
+    }
```
Comment (louisjoety) [inline src/test/java/seedu/exchangecoursemapper/FilterCoursesCommandTest.java:85]: much better 👍

**Review by louisjoety — APPROVED** [review]
