### PR TITLE
[Improvement] Fix ListUniCoursesCommand bug and extract methods in ListUniCoursesCommand to UI class

### LINKED ISSUE #159: Fix bugs for ListUniCoursesCommand
Now, when the user input is "set", the program will crash.

### LINKED ISSUE #160: Abstract UI methods into UI class for ListUniCoursesCommand
For better oop

### PR DESCRIPTION
**Pull request by Chiang-HuiXin**
Fixes #160 
Fixes #159

Changes made:
1.  Modify ListUniCoursesCommand to remove bug. 
Previously, if user input is "set" without any university name. The program will crash. To fix this bug, a new catch statement is introduced to catch the IllegalArgumentException thrown when university is null.
2. Extract methods in ListUniCoursesCommand to UI class
Move printCourseDetails to UI class for seperation of concerns

### CODE REVIEW

File: src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java [hunk 1]
```diff
@@ -12,14 +13,11 @@
 import java.util.logging.Level;
 import java.util.logging.Logger;
 
-import static seedu.exchangecoursemapper.constants.JsonKey.PU_COURSE_CODE_KEY;
-import static seedu.exchangecoursemapper.constants.JsonKey.PU_COURSE_NAME_KEY;
-import static seedu.exchangecoursemapper.constants.JsonKey.NUS_COURSE_CODE_KEY;
-import static seedu.exchangecoursemapper.constants.JsonKey.NUS_COURSE_NAME_KEY;
 import static seedu.exchangecoursemapper.constants.Messages.LINE_SEPARATOR;
 
 public class ListUniCoursesCommand extends CheckInformationCommand {
```
Comment (chewycj) [inline src/main/java/seedu/exchangecoursemapper/command/ListUniCoursesCommand.java:18]: Perhaps there can be JavaDocs comments for the classes too!

**Review by chewycj — APPROVED** [review]
LGTM!! 👍 Could also add a short JavaDocs comment for the class as well.
